### ISSUE TITLE
Old tryit app

### ISSUE THREAD

**Issue by lopezdonaque** [versatica/tryit-jssip#1]
Hi,

Could you create a repo or branch with the old tryit app please?
We were using it with an internal Turn server and the new app is missing Turn configuration.

Thanks

**Comment by ibc** [comment]
No, sorry. You can deploy the new tryit app in your own server and set hardcoded STUN/TURN servers (check the README).

**Comment by lopezdonaque** [comment]
Ok, we will do it. Thanks
