### ISSUE TITLE
Error: User Media Defined Access

### ISSUE THREAD

**Issue by akhilreddyjirra** [versatica/tryit-jssip#13]
Hello!
I'm having some problems when i try to start a call from  Browser to Browser 

I got error : **User Media Defined Access**
The Browser console logs : 
debug.js:122 JsSIP:ERROR:RTCSession emit "getusermediafailed" [error:
{name: "NotFoundError", message: "Requested device not found", constraint: undefined, toString: ƒ}
constraint:undefined
message:"Requested device not found"
name:"NotFoundError"

Note: _I have provided microphone phone setting to always allow_ 

![image](https://user-images.githubusercontent.com/9361717/35613504-596bd04c-0692-11e8-8b2b-72e3538befaa.png)

![image](https://user-images.githubusercontent.com/9361717/35613555-80537e80-0692-11e8-88b5-0bf1f7fbfc74.png)

**Comment by jmillan** [comment]
Have you cleared the cache and reloaded the browser tab?

**Comment by tm1000** [comment]
This happens for me as well and yes I cleared the cache

**Comment by Eneris** [comment]
It seems that it's trying to play "rejected" tone with device which is not connected.
Do you have by any chance have my PR included? (Ringing device is corrently not checked when disconnected)

**Comment by ibc** [comment]
Did you reject mic/webcam getUserMedia prompt? If so, go to the browser settings and allow them for the demo domain.

If not, do you have a mic and webcam in your computer? If not, getUserMedia may fail and the demo app is not ready for those cases. But it's just a demo app, so fix it within your own JsSIP based web app.

**Comment by alex-eri** [comment]
in my case camera and mic was not requested. Chrome/87

**Comment by InterLinked1** [comment]
If you override the call to CyberMegaPhone constructor with false and/or false for audio/video, does it work?
CMP2K forces audio and video by default so it may work if you force disable video, for instance.
