### ISSUE TITLE
how to set Ice gathering time out

### ISSUE THREAD

**Issue by HamidrezaRamezani** [versatica/tryit-jssip#21]
Hello 
First of all thanks for writing this beautiful demo using jssip , I  have a problem with the time this webrtc client takes to initiate a call, so I read the jssip documentation and I found a event related to this
http://jssip.net/documentation/3.2.x/api/session/#event_icecandidate

so how I can implement this into the webrtc client? I'm appreciate for any help on this issue.
I want to reduce ice gathering time out to 3-5 second actually.
Best regards

**Comment by ibc** [comment]
This is just a demo. You can clone it and adapt it to limit the gathering time by following the exact API you referenced.
