### ISSUE TITLE
how to solve globals do not match error

### ISSUE THREAD

**Issue by beatific-angel** [versatica/tryit-jssip#29]
![image](https://user-images.githubusercontent.com/64799935/181937050-b0b8a9e5-abc2-4d91-a1cf-c57d6c8e1e73.png)

what is problem?
after registered successfully, I can see this error in chrome console tab.

**Comment by ibc** [comment]
STOP reporting the same absurd thing over and over.

**Comment by beatific-angel** [comment]
to detect this, you have to explain the close reason.
otherwise I can do it continually.
if you are a developer, you have to explain and guide help request.
that is a trust developer's behavior.

**Comment by ibc** [comment]
Amazing, you really think that I have to work free for you. 

And you are wrong, you cannot do it "continually".

**Comment by beatific-angel** [comment]
strange....
I've seen a lot of developers using github, but this is the first time for a developer like you.
You must take responsibility for the products you develop.
