### ISSUE TITLE
Configuring STUN/TURN servers

### ISSUE THREAD

**Issue by x-504** [versatica/tryit-jssip#4]
Hello guys,

How can I configure the STUN and TURN servers. Not sure what is the format and also I need to set the credentials for turn. So far what I have is:

`iceServers          :
                                        [
                                                {
                                                        urls : [ 'stun:myserver:19302' ]
                                                }
                                        ]`

Can advise how to set the TURN with credentials, thank you so much in advance.

**Comment by ibc** [comment]
Please, use the JsSIP public mailing list for questions.
