### ISSUE TITLE
Got SIP response 500 "JsSIP Internal Error" back

### ISSUE THREAD

**Issue by goup2010** [versatica/tryit-jssip#5]
Hello,

I try to test tryit.jssip.net with Asterisk 14.3.0.
1060 (WebRTC) call 1061 (SIP)
Call is connected, after one min sound is stopped in asterisk log is appear: 
 Got SIP response 500 "JsSIP Internal Error" back from 192.168.1.104:5060

If using SIPML5 all forking fine.

Here full asterisk log:
 == DTLS ECDH initialized (automatic), faster PFS enabled
  == Using SIP RTP CoS mark 5
    -- Executing [1061@webrtc:1] Dial("SIP/1060-00000019", "SIP/1061") in new stack
  == Using SIP RTP CoS mark 5
    -- Called SIP/1061
    -- SIP/1061-0000001a is ringing
       > 0x7fbf14009110 -- Probation passed - setting RTP source address to 192.168.1.152:55334
    -- SIP/1061-0000001a answered SIP/1060-00000019
    -- Channel SIP/1061-0000001a joined 'simple_bridge' basic-bridge <f8993550-807a-4113-8444-ca2a13aa0e33>
    -- Channel SIP/1060-00000019 joined 'simple_bridge' basic-bridge <f8993550-807a-4113-8444-ca2a13aa0e33>
       > 0x7fbf14009110 -- Probation passed - setting RTP source address to 192.168.1.152:55334
       > 0x7fbec403a9e0 -- Probation passed - setting RTP source address to 192.168.1.104:53248
    -- **Got SIP response 500 "JsSIP Internal Error" back from 192.168.1.104:5060**
       > 0x7fbec403a9e0 -- Probation passed - setting RTP source address to 192.168.1.104:53248
[Mar 10 21:08:11] WARNING[4801]: netsock2.c:210 ast_sockaddr_split_hostport: Port missing in (null)

**Comment by ibc** [comment]
Sorry, this is JsSIP project, not Asterisk.

**Comment by goup2010** [comment]
JSSIP is one part of communication.
Normaly to send here problems.

**Comment by ibc** [comment]
Chrome/Firefox is also there, right? Did you report the same issue into the Chrome bug tracker?

To be 100% clear: We don't know your Asterisk configuration, we don't even know the current exact status of WebRTC in Asterisk . We just know that JsSIP properly deals with the WebRTC API provided by the browser and properly implements the SIP protocol. We are not responsible of how the different WebRTC engines (Chrome, Firefox, Asterisk, etc) deal one with each other.

> Normaly to send here problems.

Yes, unfortunately is normal to get here all the reports about WebRTC issues with Asterisk. It just shouldn't be.

**Comment by goup2010** [comment]
I apologize for the trouble.

**Comment by ibc** [comment]
You may want to ask in the JsSIP public mailing list about your problem with Asterisk, but we cannot keep it open here in the JsSIP issue tracker.
