### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by juha-h** [versatica/tryit-jssip#6]
I tried to follow the installation instructions, but 'npm install' failed.  Did I do make some stupid mistake (I don't know much about npm)? I was not able to find ibc/react-notification-system from github.
-- Juha

h@rautu:/usr/src/orig/tryit-jssip$ npm install
|nter passphrase for key '/home/jh/.ssh/id_rsa': -
npm ERR! git clone git@github.com:github:ibc/react-notification-system Cloning into bare repository '/home/jh/.npm/_git-remotes/git-github-com-github-ibc-react-notification-system-e9024493'...
npm ERR! git clone git@github.com:github:ibc/react-notification-system fatal: remote error: 
npm ERR! git clone git@github.com:github:ibc/react-notification-system    is not a valid repository name
npm ERR! git clone git@github.com:github:ibc/react-notification-system   Email support@github.com for help

**Comment by ibc** [comment]
Which `node` and `npm` versions?

**Comment by juha-h** [comment]
I tried this on Debian testing (Stretch):

jh@rautu:/var/www/tryit-jssip$ nodejs -v
v4.7.2
jh@rautu:/var/www/tryit-jssip$ npm -v
1.4.21

**Comment by ibc** [comment]
Such a `npm` version is to old. I recommend upgrading to Node 6 (the current stable):

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Anyhow, Node 4 comes with NPM 2, so I don't fully understand how you have NPM 1.4.21.

**Comment by juha-h** [comment]
Iñaki Baz Castillo writes:

> Such a `npm` version is to old. I recommend upgrading to Node 6 (the
> current stable): 
> 
> https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

OK, I'll try that.

> Anyhow, Node 4 comes with NPM 2, so I don't fully understand how you
> have NPM 1.4.21.

Below is what 'apt-get install npm' installed on Debian Stretch (it
installed npm 1.4.21).

-- Juha

# apt-get install npm
...
Need to get 6,842 kB of archives.
After this operation, 20.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ftp.fi.debian.org/debian stretch/main amd64 gyp all 0.1+20150913git1f374df9-1 [266 kB]
Get:2 http://ftp.fi.debian.org/debian stretch/main amd64 libjs-node-uuid all 1.4.0-1 [12.6 kB]
Get:3 http://ftp.fi.debian.org/debian stretch/main amd64 libssl1.0-dev amd64 1.0.2k-1 [1,557 kB]
Get:4 http://ftp.fi.debian.org/debian stretch/main amd64 libuv1 amd64 1.9.1-3 [84.4 kB]
Get:5 http://ftp.fi.debian.org/debian stretch/main amd64 libuv1-dev amd64 1.9.1-3 [104 kB]
Get:6 http://ftp.fi.debian.org/debian stretch/main amd64 nodejs amd64 4.7.2~dfsg-2+b1 [3,452 kB]
Get:7 http://ftp.fi.debian.org/debian stretch/main amd64 node-async all 0.8.0-1 [24.6 kB]
Get:8 http://ftp.fi.debian.org/debian stretch/main amd64 node-builtin-modules all 1.1.1-1 [3,298 B]
Get:9 http://ftp.fi.debian.org/debian stretch/main amd64 node-fs.realpath all 1.0.0-1 [5,522 B]
Get:10 http://ftp.fi.debian.org/debian stretch/main amd64 node-hosted-git-info all 2.1.5-1 [5,696 B]
Get:11 http://ftp.fi.debian.org/debian stretch/main amd64 node-wrappy all 1.0.2-1 [3,114 B]
Get:12 http://ftp.fi.debian.org/debian stretch/main amd64 node-once all 1.4.0-2 [3,356 B]
Get:13 http://ftp.fi.debian.org/debian stretch/main amd64 node-inflight all 1.0.6-1 [3,334 B]
Get:14 http://ftp.fi.debian.org/debian stretch/main amd64 node-is-builtin-module all 1.0.0-1 [2,860 B]
Get:15 http://ftp.fi.debian.org/debian stretch/main amd64 node-isexe all 1.1.2-1 [3,948 B]
Get:16 http://ftp.fi.debian.org/debian stretch/main amd64 node-node-uuid all 1.4.0-1 [9,194 B]
Get:17 http://ftp.fi.debian.org/debian stretch/main amd64 node-path-is-absolute all 1.0.0-1 [3,266 B]
Get:18 http://ftp.fi.debian.org/debian stretch/main amd64 node-pseudomap all 1.0.2-1 [3,504 B]
Get:19 http://ftp.fi.debian.org/debian stretch/main amd64 node-spdx-license-ids all 1.2.2-1 [4,754 B]
Get:20 http://ftp.fi.debian.org/debian stretch/main amd64 node-spdx-correct all 1.0.2-1 [3,678 B]
Get:21 http://ftp.fi.debian.org/debian stretch/main amd64 node-spdx-expression-parse all 1.0.4-1 [12.1 kB]
Get:22 http://ftp.fi.debian.org/debian stretch/main amd64 node-underscore all 1.8.3~dfsg-1 [37.6 kB]
Get:23 http://ftp.fi.debian.org/debian stretch/main amd64 node-validate-npm-package-license all 3.0.1-1 [3,442 B]
Get:24 http://ftp.fi.debian.org/debian stretch/main amd64 node-yallist all 2.0.0-1 [5,362 B]
Get:25 http://ftp.fi.debian.org/debian stretch/main amd64 libjs-inherits all 2.0.3-1 [2,762 B]
Get:26 http://ftp.fi.debian.org/debian stretch/main amd64 node-abbrev all 1.0.9-1 [3,668 B]
Get:27 http://ftp.fi.debian.org/debian stretch/main amd64 node-ansi all 0.3.0-2 [8,608 B]
Get:28 http://ftp.fi.debian.org/debian stretch/main amd64 node-ansi-color-table all 1.0.0-1 [4,408 B]
Get:29 http://ftp.fi.debian.org/debian stretch/main amd64 node-archy all 1.0.0-1 [4,052 B]
Get:30 http://ftp.fi.debian.org/debian stretch/main amd64 node-balanced-match all 0.4.2-1 [3,982 B]
Get:31 http://ftp.fi.debian.org/debian stretch/main amd64 node-inherits all 2.0.3-1 [3,744 B]
Get:32 http://ftp.fi.debian.org/debian stretch/main amd64 node-block-stream all 0.0.9-1 [4,488 B]
Get:33 http://ftp.fi.debian.org/debian stretch/main amd64 node-concat-map all 0.0.1-1 [3,462 B]
Get:34 http://ftp.fi.debian.org/debian stretch/main amd64 node-brace-expansion all 1.1.6-1 [5,672 B]
Get:35 http://ftp.fi.debian.org/debian stretch/main amd64 node-delayed-stream all 0.0.5-1 [4,482 B]
Get:36 http://ftp.fi.debian.org/debian stretch/main amd64 node-combined-stream all 0.0.5-1 [4,918 B]
Get:37 http://ftp.fi.debian.org/debian stretch/main amd64 node-cookie-jar all 0.3.1-1 [3,570 B]
Get:38 http://ftp.fi.debian.org/debian stretch/main amd64 node-forever-agent all 0.5.1-1 [3,066 B]
Get:39 http://ftp.fi.debian.org/debian stretch/main amd64 node-mime all 1.3.4-1 [11.8 kB]
Get:40 http://ftp.fi.debian.org/debian stretch/main amd64 node-form-data all 0.1.0-1 [6,084 B]
Get:41 http://ftp.fi.debian.org/debian stretch/main amd64 node-minimatch all 3.0.3-1 [12.8 kB]
Get:42 http://ftp.fi.debian.org/debian stretch/main amd64 node-glob all 7.1.1-1 [18.4 kB]
Get:43 http://ftp.fi.debian.org/debian stretch/main amd64 node-rimraf all 2.5.4-2 [7,482 B]
Get:44 http://ftp.fi.debian.org/debian stretch/main amd64 node-mkdirp all 0.5.0-1 [4,634 B]
Get:45 http://ftp.fi.debian.org/debian stretch/main amd64 node-graceful-fs all 4.1.11-1 [10.8 kB]
Get:46 http://ftp.fi.debian.org/debian stretch/main amd64 node-fstream all 1.0.10-1 [18.1 kB]
Get:47 http://ftp.fi.debian.org/debian stretch/main amd64 node-fstream-ignore all 0.0.6-2 [5,536 B]
Get:48 http://ftp.fi.debian.org/debian stretch/main amd64 node-github-url-from-git all 1.4.0-1 [3,730 B]
Get:49 http://ftp.fi.debian.org/debian stretch/main amd64 nodejs-dev amd64 4.7.2~dfsg-2+b1 [530 kB]
Get:50 http://ftp.fi.debian.org/debian stretch/main amd64 node-nopt all 3.0.6-3 [9,538 B]
Get:51 http://ftp.fi.debian.org/debian stretch/main amd64 node-npmlog all 0.0.4-1 [5,516 B]
Get:52 http://ftp.fi.debian.org/debian stretch/main amd64 node-osenv all 0.1.0-1 [3,734 B]
Get:53 http://ftp.fi.debian.org/debian stretch/main amd64 node-tunnel-agent all 0.3.1-1 [3,840 B]
Get:54 http://ftp.fi.debian.org/debian stretch/main amd64 node-json-stringify-safe all 5.0.0-1 [3,356 B]
Get:55 http://ftp.fi.debian.org/debian stretch/main amd64 node-qs all 2.2.4-1 [8,474 B]
Get:56 http://ftp.fi.debian.org/debian stretch/main amd64 node-request all 2.26.1-1 [15.7 kB]
Get:57 http://ftp.fi.debian.org/debian stretch/main amd64 node-semver all 5.3.0-1 [21.9 kB]
Get:58 http://ftp.fi.debian.org/debian stretch/main amd64 node-tar all 2.2.1-1 [17.6 kB]
Get:59 http://ftp.fi.debian.org/debian stretch/main amd64 node-which all 1.2.11-1 [4,946 B]
Get:60 http://ftp.fi.debian.org/debian stretch/main amd64 node-gyp all 3.4.0-1 [28.9 kB]
Get:61 http://ftp.fi.debian.org/debian stretch/main amd64 node-ini all 1.1.0-1 [4,720 B]
Get:62 http://ftp.fi.debian.org/debian stretch/main amd64 node-lockfile all 0.4.1-1 [5,150 B]
Get:63 http://ftp.fi.debian.org/debian stretch/main amd64 node-lru-cache all 4.0.2-1 [7,412 B]
Get:64 http://ftp.fi.debian.org/debian stretch/main amd64 node-mute-stream all 0.0.7-1 [4,344 B]
Get:65 http://ftp.fi.debian.org/debian stretch/main amd64 node-normalize-package-data all 2.3.5-2 [10.5 kB]
Get:66 http://ftp.fi.debian.org/debian stretch/main amd64 node-read all 1.0.7-1 [4,540 B]
Get:67 http://ftp.fi.debian.org/debian stretch/main amd64 node-read-package-json all 1.2.4-1 [7,740 B]
Get:68 http://ftp.fi.debian.org/debian stretch/main amd64 node-retry all 0.6.0-1 [6,124 B]
Get:69 http://ftp.fi.debian.org/debian stretch/main amd64 node-sha all 1.2.3-1 [4,064 B]
Get:70 http://ftp.fi.debian.org/debian stretch/main amd64 node-slide all 1.1.4-1 [6,078 B]
Get:71 http://ftp.fi.debian.org/debian stretch/main amd64 npm all 1.4.21+ds-2 [354 kB]
Fetched 6,842 kB in 28s (237 kB/s)                                             
...

**Comment by ibc** [comment]
AFAIK Debian does not yet come with a "pro" version of Node & NPM.

**Comment by juha-h** [comment]
After installing latest Node.js from the link above, both npm commands listed in README.md worked, but the second needed to be run as root user. Perhaps it would be a good idea to change prefix of the second npm command from $ to #.

**Comment by ibc** [comment]
Depending on your NPM settings, you may have global NPM modules installed into your home (rather than in `/usr/...`), so root/sudo is not required.
