### ISSUE TITLE
Cannot seem to force the static config in index.html

### ISSUE THREAD

**Issue by tedd77** [versatica/tryit-jssip#8]
Hello,

I am unable to make the application read the static settings in index.html
No matter the changes , when accessing the site it shows all empty except for
the websocket : wss://tryit.jssip.net:10443 which is different anyway from what I set.
Could you please advise ?
Thank you

**Comment by jmillan** [comment]
@tedd77,

You need to clean up the cache in your browser in order to get rid of the previous config.

**Comment by tedd77** [comment]
@jmillan 
Thank you for the reply, but apparently I did not properly install the package.
Please correct my steps if any and help me out figure why the problem is still there
1. git clone https://github.com/versatica/tryit-jssip.git
2. npm install
3. npm install -g gulp-cli

now I can see a new folder called node_modules inside the tryit-jssip

The index .html refers to 2 files
tryit-jssip.js
tryit-jssip.css
I copied them from a clone I made earlier from git tryit.jssip.net.mirror

Yet there are 2 files missing in /resources/js 
callstats-jssip.min.js
callstats-jssip.js

Despite the missing files, I can access the page but again the static settings in index.html are not into effect.


I know I made a mess however I did not see a real structured way for doing it.
The reason I am insisting on hosting it myself is due to a hack required so that it works with asterisk.

Thank you in advance for your help.

**Comment by ibc** [comment]
Why are you doing that instead of just following given steps? You miss:

> Build the app (check the gulpfile file for details):
>
>* gulp prod generates the app in production/minified mode.
>* gulp dev generates the app in development mode.
>* gulp live generates the app in development mode, opens the local website and watches for changes in the source code.
>
> Once built, the out/ directory is created with all the HTML, CSS and JavaScript files to be deployed in your own server.

**Comment by tedd77** [comment]
Unable to build please see errors below

gulp prod
/var/www/html/tryit-jssip/gulpfile.js:23
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at execute (/usr/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:36:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp-cli/index.js:173:63)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)

**Comment by ibc** [comment]
You need modern Node, 4.8.X or 6.X.X or 7.X.X.

**Comment by tedd77** [comment]
Thank you. I had to build it on a new machine and it worked.
the out directory was created yet the following 2 files are still showing red next to them as if they are linked to an unknown location
callstats-jssip.min.js
callstats-jssip.js

Despite that fact , hard coded config in index.html are not reflected into the browser.
I cleared the cache and I even accessed it from a new machine the setting is still the default set into tryit-jssip.js

Thank you for your support and patience.

**Comment by tedd77** [comment]
Could you please let me know the version and type of the linux OS you are using ?

**Comment by ibc** [comment]
Forget about callstats stuff, those files are not included.

Things work. I've just tested it. Please, edit `window.SETTINGS` in the `/index.html` file and then run your preferred `gulp` task to build the app. You may need to delete your `localStorage` for those settings to take effect (I don't remember).

**Comment by tedd77** [comment]
@ibc  Thank you. I was able to figure out how to fix that by changing the tryit-jssip.js
in the section that starts with 
var DEFAULT_SETTINGS = {

My problem now is registering with asterisk
Do you mind telling me your setup? with which SIP WEBRTC are you able to make it work ? and what tweaks you had to do to make it work ?

**Comment by ibc** [comment]
> @ibc  Thank you. I was able to figure out how to fix that by changing the tryit-jssip.js
in the section that starts with 
var DEFAULT_SETTINGS = {

That's wrong. You should not do that but, instead, what I told you in my previous comment.

> My problem now is registering with asterisk
Do you mind telling me your setup? with which SIP WEBRTC are you able to make it work ? and what tweaks you had to do to make it work ?

The demo uses Kamailio as registrar. There are too many users out there successfully using JsSIP with Asterisk. Please, look for posts, threads, forums, etc. in Internet.

**Comment by tedd77** [comment]
@ibc  I was looking into Kamailio
I posted a request on the mailing list for asterisk. Hope someone will help and I will keep on searching.
