### ISSUE TITLE
Feature request: Add config for custom STUN server

### ISSUE THREAD

**Issue by saidmasoud** [versatica/tryit-jssip#9]
As mentioned [here](https://groups.google.com/forum/#!topic/jssip/86TgmoGWYx8), some orgs do not allow access to external STUN servers. Requesting a configuration option be added for custom STUN servers.

**Comment by ibc** [comment]
I understand your point, but tryit-jssip is just a demo, not a product or service. It's intended for users to play with it and show how to build a JsSIP based app.
